variables:
  ROLE_ARN: arn:aws:iam::${ACCOUNT_ID}:role/${ROLE_NAME}

before_script:
    - mkdir -p ~/.aws
    - echo "${CI_JOB_JWT_V2}" > /tmp/web_identity_token
    - echo -e "[profile oidc]\nrole_arn=${ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config

test-oidc:
  image: 
    name: amazon/aws-cli:latest
    entrypoint: [""]
  variables:
    AWS_REGION: ap-southeast-2
    AWS_PROFILE: oidc
  script:
      - aws sts get-caller-identity

