version: '2.1'

orbs:
 # import CircleCI's aws-cli orb
 aws-cli: circleci/aws-cli@3.1

jobs:
 aws-example:
   docker:
     - image: cimg/aws:2022.06

   steps:
     - checkout
     # run the aws-cli/setup command from the orb
     - aws-cli/setup:
        role-arn: 'arn:aws:iam::${ACCOUNT_ID}:role/${ROLE_NAME}'
        # aws-region: ap-southeast-2
        # optional parameters
        #  profile-name: "OIDC-PROFILE"
        role-session-name: example-session
        # session-duration: 1800

     - when:
        condition:
          equal: [ 'placeholder', << pipeline.git.branch >> ]

        steps:
          - run:
              name: 'AWS STS'
              command: 'aws sts get-caller-identity'
    
workflows:
 OIDC-with-AWS:
   jobs:
     - aws-example:
         # must use a valid CircleCI context (https://circleci.com/docs/contexts/)
         context: aws
         filters:
            branches:
              only:
                - placeholder